### PR TITLE
Put CVariant into own namespace

### LINKED ISSUE #319: Kodi crashes when a PVR stream is stopped via remote app (unhandled bad_variant_access exception)
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi crashes when playing a PVR stream via "inputstream.ffmpegdirect" plugin and using remote control app, Yatse, to start and stop the stream.
Playing starts normally. Stopping results in crash.
Kodi does not crash when playing files from the disk. Also it does not crash when playing PVR streams via "inputstream.adaptive" plugin.
I have identified crash place and suggested a patch to fix, see below.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should not crash when stopping a PVR stream with remote control app.

## Actual Behavior

Kodi crashes due to unhandled bad_variant_access exception.

## Possible Fix

The crash happens when remote app makes RPC call without parameters, but webserver tries to parse the empty parameters string eventually calling the CVariant.size() in a Null constant.
Catching this exception fixes the problem.
```
--- a/xbmc/interfaces/json-rpc/JSONServiceDescription.cpp.bak	2025-01-15 17:14:15.000000000 -0500
+++ b/xbmc/interfaces/json-rpc/JSONServiceDescription.cpp	2025-03-23 19:12:50.625726613 -0400
@@ -1387,13 +1387,15 @@
       }
 
       // Check if there were unnecessary parameters
+      try {
       if (handled < requestParameters.size())
       {
         errorData["message"] = "Too many parameters";
         outputParameters = errorData;
         return InvalidParams;
       }
-
+      } catch (std::bad_variant_access e) {
+      }
       return OK;
     }
     else
```

### To Reproduce

1. Start playing a PVR stream via iptvsimple plugin.
2. Press Stop button in Yatse.

### Debuglog

The debuglog can be found here:
https://pastebin.com/Z4iq51Lk

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21.2 Omega

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by David-EIPI**
Put CVariant into ffmpegdirect namespace to avoid collisions with CVariant in XBMC tree.
This fixes Kodi crashes as described in https://github.com/xbmc/inputstream.ffmpegdirect/issues/319

### CODE REVIEW

File: src/stream/url/Variant.h [hunk 1]
```diff
@@ -25,6 +25,8 @@ double str2double(const std::wstring &str, double fallback = 0.0);
 #pragma pack(8)
 #endif
 
+namespace ffmpegdirect {
```
Comment (phunkyfish) [inline src/stream/url/Variant.h]: Open bracket should be on the following line.

**Review by phunkyfish — CHANGES_REQUESTED** [review]
Just one minor. Otherwise looks good.

Would you like this to be released? If so you would need to add a commit that updates the addon.xml.in (increment the micro version as its fix) and add a changelog entry.

**Comment by David-EIPI** [comment]
Yes, I think this is an important fix that needs to go to release. I did the requested edits.

**Comment by phunkyfish** [comment]
Released. Should appear on binary addon servers over the next while.

Thanks for the contribution!

**Comment by basilgello** [comment]
@phunkyfish This also hits Omega. Debian's approaching full freeze now so I upgraded and was immediately struck. I will make a targeted bugfix release into Debian but I'd maake one more upstream release of 21.3.8 just in case.
